services:
  website-dev:
    image: node:20-alpine
    container_name: website-dev
    working_dir: /app

    command: sh -c "npm install && npm run dev"

    ports:
      - "3000:3000"

    env_file:
      - ../../website_data/.env.local   # âœ… ADD THIS
      
    environment:
      DATABASE_URL: postgresql://dev:devpass@website-dev-db:5432/devdb
      NEXTAUTH_SECRET: dev-secret
      NEXTAUTH_URL: http://192.168.0.15:3000


    volumes:
      - ../../website_data:/app

    depends_on:
      - website-dev-db

    networks:
      - dev

  website-dev-db:
    image: postgres:16
    container_name: website-dev-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - website_dev_db:/var/lib/postgresql/data
    networks:
      - dev

networks:
  dev:

volumes:
  website_dev_db:
