services:
  website-dev:
    image: node:20-alpine
    container_name: website-dev
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ../../website_data:/app
      - website_dev_node_modules:/app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - db
    networks:
      - dev

  db:
    image: postgres:16
    ports:
      - "5432:5432" 
    container_name: website-dev-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - website_dev_db:/var/lib/postgresql/data
    networks:
      - dev

networks:
  dev:

volumes:
  website_dev_db:
  website_dev_node_modules:
